name: Deploy react app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["13.x"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: npm install
      - name: registry github user
        run: |
          git config --global user.email <jesus_beltran011@outlook.com>
          git config --global user.name <AlexisBeltran>
      - name: deploy the app
        run: npm run deploy
        env:
        APIClima: ${{ secrets.APIClima }}
